// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZEsA3jOq02_BCBahJSxHZ9P9L3Dt_5GY',
    appId: '1:67980763839:web:db7856fbc63a47789d9c0a',
    messagingSenderId: '67980763839',
    projectId: 'learning-firedart-usethis',
    authDomain: 'learning-firedart-usethis.firebaseapp.com',
    storageBucket: 'learning-firedart-usethis.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChR3s0Q7_MBIrcTgmMSnyyeHO1ITmmOns',
    appId: '1:67980763839:android:6673c7e97652bae99d9c0a',
    messagingSenderId: '67980763839',
    projectId: 'learning-firedart-usethis',
    storageBucket: 'learning-firedart-usethis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY-BUhZFoCGIm5yuhOK7gnU55E4KRqQUU',
    appId: '1:67980763839:ios:bf029414880c61209d9c0a',
    messagingSenderId: '67980763839',
    projectId: 'learning-firedart-usethis',
    storageBucket: 'learning-firedart-usethis.firebasestorage.app',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY-BUhZFoCGIm5yuhOK7gnU55E4KRqQUU',
    appId: '1:67980763839:ios:bf029414880c61209d9c0a',
    messagingSenderId: '67980763839',
    projectId: 'learning-firedart-usethis',
    storageBucket: 'learning-firedart-usethis.firebasestorage.app',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZEsA3jOq02_BCBahJSxHZ9P9L3Dt_5GY',
    appId: '1:67980763839:web:4735f00da9d99f549d9c0a',
    messagingSenderId: '67980763839',
    projectId: 'learning-firedart-usethis',
    authDomain: 'learning-firedart-usethis.firebaseapp.com',
    storageBucket: 'learning-firedart-usethis.firebasestorage.app',
  );
}
